package com.jml.inferrer.rest;

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.AnnotationExpr;
import com.github.javaparser.ast.expr.SingleMemberAnnotationExpr;
import com.github.javaparser.ast.expr.NormalAnnotationExpr;
import com.jml.inferrer.analysis.MethodSpecificationInferrer;
import com.jml.inferrer.embedder.InferrerSpecConverter;
import com.jml.inferrer.model.MethodSpecification;
import com.jml.spec.MethodSpec;
import com.jml.spec.openapi.OperationKey;
import com.jml.spec.openapi.OperationSpec;
import com.jml.spec.openapi.OpenApiJmlExtension;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * RQ2 Phase 2A.6 — Spring/JAX-RS REST endpoint inferrer.
 *
 * <p>Walks {@code @RestController} (or {@code @Controller}) classes in the
 * source, finds handler methods annotated with HTTP-verb mappings
 * ({@code @GetMapping}, {@code @PostMapping}, {@code @RequestMapping},
 * {@code @PutMapping}, {@code @DeleteMapping}, {@code @PatchMapping}), runs
 * the {@link MethodSpecificationInferrer} on each handler, converts the
 * result to a {@link MethodSpec} via {@link InferrerSpecConverter}, and
 * produces an OpenAPI document carrying the inferred specifications as
 * {@code x-jml-*} extensions per
 * {@code journal/rq2_embedding_design.md} §6.</p>
 *
 * <p>Spring is not a runtime dependency of this class — only the source-AST
 * shape of the annotations is recognised. The same approach handles
 * JAX-RS-style {@code @GET}, {@code @POST}, etc. via the same name-based
 * detection.</p>
 *
 * <p>The class-level mapping prefix on {@code @RequestMapping} is honoured
 * (so {@code @RequestMapping("/api")} on the class plus
 * {@code @GetMapping("/orders")} on the method yields route
 * {@code "/api/orders"}). Method-level mappings without an explicit verb
 * default to {@code GET}.</p>
 */
public class RestEndpointInferrer {

    private final MethodSpecificationInferrer inferrer;

    public RestEndpointInferrer() {
        this(new MethodSpecificationInferrer());
    }

    public RestEndpointInferrer(MethodSpecificationInferrer inferrer) {
        this.inferrer = inferrer;
    }

    /**
     * Walk a parsed compilation unit and return per-endpoint specs.
     */
    public Map<OperationKey, OperationSpec> inferEndpoints(CompilationUnit cu) {
        Map<OperationKey, OperationSpec> result = new LinkedHashMap<>();
        for (ClassOrInterfaceDeclaration clazz : cu.findAll(ClassOrInterfaceDeclaration.class)) {
            if (!isController(clazz)) continue;
            String prefix = classMappingPrefix(clazz);
            for (MethodDeclaration method : clazz.getMethods()) {
                Optional<HandlerInfo> handler = handlerInfo(method);
                if (handler.isEmpty()) continue;
                HandlerInfo info = handler.get();
                String fullRoute = combineRoute(prefix, info.route());
                MethodSpecification spec = inferrer.inferSpecification(method);
                MethodSpec embeddable = InferrerSpecConverter.toEmbeddable(spec);
                result.put(new OperationKey(fullRoute, info.verb()), toOperationSpec(embeddable));
            }
        }
        return result;
    }

    /**
     * Convenience: produce a complete OpenAPI document containing only the
     * inferred specifications (no operation summaries, parameters, or
     * response shapes — those are downstream concerns left to the OpenAPI
     * generation pipeline this output is meant to be merged into).
     */
    public String inferToOpenApi(CompilationUnit cu) {
        Map<OperationKey, OperationSpec> specs = inferEndpoints(cu);
        return OpenApiJmlExtension.write(null, specs);
    }

    /**
     * Convenience: produce the sidecar JSON form (per design doc §6.4) for
     * cases where the OpenAPI document is generated by the framework and
     * cannot be modified.
     */
    public String inferToSidecar(CompilationUnit cu) {
        Map<OperationKey, OperationSpec> specs = inferEndpoints(cu);
        return OpenApiJmlExtension.writeSidecar(specs);
    }

    private static boolean isController(ClassOrInterfaceDeclaration clazz) {
        for (AnnotationExpr ann : clazz.getAnnotations()) {
            String name = ann.getNameAsString();
            if ("RestController".equals(name) || "Controller".equals(name)
                    || "Path".equals(name)) return true;
        }
        return false;
    }

    private static String classMappingPrefix(ClassOrInterfaceDeclaration clazz) {
        for (AnnotationExpr ann : clazz.getAnnotations()) {
            String name = ann.getNameAsString();
            if ("RequestMapping".equals(name) || "Path".equals(name)) {
                String value = readAnnotationStringValue(ann);
                if (value != null) return value;
            }
        }
        return "";
    }

    private static Optional<HandlerInfo> handlerInfo(MethodDeclaration method) {
        for (AnnotationExpr ann : method.getAnnotations()) {
            String name = ann.getNameAsString();
            String verb = mapAnnotationToVerb(name);
            if (verb == null) continue;
            String route = readAnnotationStringValue(ann);
            if (route == null) route = "";
            return Optional.of(new HandlerInfo(verb, route));
        }
        return Optional.empty();
    }

    /**
     * Map a Spring/JAX-RS HTTP-verb annotation name to the canonical verb,
     * or null if the annotation is not a handler mapping.
     */
    private static String mapAnnotationToVerb(String annotationName) {
        return switch (annotationName) {
            case "GetMapping", "GET" -> "GET";
            case "PostMapping", "POST" -> "POST";
            case "PutMapping", "PUT" -> "PUT";
            case "DeleteMapping", "DELETE" -> "DELETE";
            case "PatchMapping", "PATCH" -> "PATCH";
            // RequestMapping with no verb defaults to GET; if a verb is
            // present in the `method` element, downstream callers can refine
            // by re-reading the annotation. The simple form is the common
            // case.
            case "RequestMapping" -> "GET";
            default -> null;
        };
    }

    /**
     * Extract the {@code value} (or implicit single member) of a
     * {@code @SomeMapping("...")} or {@code @SomeMapping(value = "...")}
     * annotation. Returns null if no string value is present.
     */
    private static String readAnnotationStringValue(AnnotationExpr ann) {
        if (ann instanceof SingleMemberAnnotationExpr sm) {
            String s = sm.getMemberValue().toString();
            return stripQuotes(s);
        }
        if (ann instanceof NormalAnnotationExpr norm) {
            for (var pair : norm.getPairs()) {
                if (pair.getNameAsString().equals("value")
                        || pair.getNameAsString().equals("path")) {
                    return stripQuotes(pair.getValue().toString());
                }
            }
        }
        return null;
    }

    private static String stripQuotes(String s) {
        if (s == null) return null;
        s = s.trim();
        if (s.startsWith("\"") && s.endsWith("\"") && s.length() >= 2) {
            return s.substring(1, s.length() - 1);
        }
        // Array form @GetMapping({"/a", "/b"}) — pick the first element.
        if (s.startsWith("{") && s.endsWith("}")) {
            String inner = s.substring(1, s.length() - 1).trim();
            int comma = inner.indexOf(',');
            if (comma > 0) inner = inner.substring(0, comma).trim();
            return stripQuotes(inner);
        }
        return s;
    }

    private static String combineRoute(String prefix, String route) {
        if (prefix.isEmpty()) return route.isEmpty() ? "/" : route;
        if (route.isEmpty()) return prefix;
        if (prefix.endsWith("/") && route.startsWith("/")) return prefix + route.substring(1);
        if (!prefix.endsWith("/") && !route.startsWith("/")) return prefix + "/" + route;
        return prefix + route;
    }

    private static OperationSpec toOperationSpec(MethodSpec ms) {
        return new OperationSpec(
                ms.requires(),
                ms.ensures(),
                ms.assignable(),
                ms.loopInvariant(),
                ms.signals(),
                ms.version());
    }

    private record HandlerInfo(String verb, String route) {
    }
}
