package com.jml.inferrer.ci;

import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * {@code jml-ci summary} — render a markdown summary suitable for posting
 * as a PR comment, by reading the JSON reports from previous
 * {@code jml-ci infer} and {@code jml-ci verify} runs.
 *
 * <p>The summary is collapsed by default so the PR review surface stays
 * uncluttered; clicking expands it to show the per-file outcomes.</p>
 */
class SummaryCommand {

    int execute(Map<String, String> opts, PrintStream out) throws Exception {
        String inferReportPath = opts.getOrDefault("infer-report", ".jml-cache/infer-report.json");
        String verifyReportPath = opts.getOrDefault("verify-report", ".jml-cache/verify-report.json");
        String format = opts.getOrDefault("format", "markdown");
        String outPath = opts.get("out");

        String inferReport = readIfExists(inferReportPath);
        String verifyReport = readIfExists(verifyReportPath);

        String rendered = "json".equalsIgnoreCase(format)
                ? renderJson(inferReport, verifyReport)
                : renderMarkdown(inferReport, verifyReport);

        if (outPath != null) {
            Files.createDirectories(Paths.get(outPath).getParent());
            Files.writeString(Paths.get(outPath), rendered);
            out.printf("[jml-ci summary] %s written to %s%n", format, outPath);
        } else {
            out.println(rendered);
        }
        return 0;
    }

    private static String readIfExists(String path) throws Exception {
        Path p = Paths.get(path);
        return Files.exists(p) ? Files.readString(p) : "";
    }

    private static String renderMarkdown(String inferReport, String verifyReport) {
        StringBuilder md = new StringBuilder();
        md.append("## JML inference summary\n\n");

        Counts ic = parseInferCounts(inferReport);
        md.append("**Inference**: ")
                .append(ic.inferred).append(" inferred, ")
                .append(ic.cached).append(" cached, ")
                .append(ic.errors).append(" errors.\n\n");

        Counts vc = parseVerifyCounts(verifyReport);
        md.append("**Verification**: ");
        if (verifyReport.contains("\"status\": \"skipped\"")) {
            md.append("skipped (OpenJML not available in this environment).\n");
        } else {
            md.append(vc.verified).append(" verified, ")
                    .append(vc.flagged).append(" flagged, ")
                    .append(vc.errors).append(" errors.\n");
        }

        md.append("\n<details><summary>Inferred file outcomes</summary>\n\n");
        md.append("```json\n");
        md.append(inferReport.isEmpty() ? "(no infer report present)" : inferReport);
        md.append("```\n\n</details>\n\n");

        md.append("<sub>Generated by `jml-ci`. Specifications are informational; ")
                .append("flagged clauses do not block the merge by default. ")
                .append("See journal/rq4_cicd_design.md for the workflow design.</sub>\n");

        return md.toString();
    }

    private static String renderJson(String inferReport, String verifyReport) {
        Counts ic = parseInferCounts(inferReport);
        Counts vc = parseVerifyCounts(verifyReport);
        return String.format(
                "{\n  \"infer\": { \"inferred\": %d, \"cached\": %d, \"errors\": %d },\n"
                        + "  \"verify\": { \"verified\": %d, \"flagged\": %d, \"errors\": %d }\n}\n",
                ic.inferred, ic.cached, ic.errors,
                vc.verified, vc.flagged, vc.errors);
    }

    private static Counts parseInferCounts(String json) {
        Counts c = new Counts();
        c.inferred = extractInt(json, "\\\"inferred\\\":\\s*(\\d+)");
        c.cached = extractInt(json, "\\\"cached\\\":\\s*(\\d+)");
        c.errors = extractInt(json, "\\\"errors\\\":\\s*(\\d+)");
        return c;
    }

    private static Counts parseVerifyCounts(String json) {
        Counts c = new Counts();
        c.verified = extractInt(json, "\\\"verified\\\":\\s*\\\"?(\\d+)");
        c.flagged = extractInt(json, "\\\"flagged\\\":\\s*\\\"?(\\d+)");
        c.errors = extractInt(json, "\\\"errors\\\":\\s*\\\"?(\\d+)");
        return c;
    }

    private static int extractInt(String text, String pattern) {
        Matcher m = Pattern.compile(pattern).matcher(text);
        if (m.find()) {
            try { return Integer.parseInt(m.group(1)); }
            catch (NumberFormatException ignored) { return 0; }
        }
        return 0;
    }

    private static class Counts {
        int inferred;
        int cached;
        int errors;
        int verified;
        int flagged;
    }
}
